production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/interncompass_solr
    auto_commit_after_request: false
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
    path: /solr/development
    auto_commit_after_request: false

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    path: /solr/test
    auto_commit_after_request: false
